export const StyledObject = {
  mainMenu: {
    fontFamily: "Nunito",
    width: "90%",
    backgroundColor: "white",
    margin: "5vh auto auto auto",
    overflowY: "scroll",
    height: "60vh",
  },
  th: {
    color: "black",
    fontWeight: "700",
    padding: "5px",
    textAlign: "center",
  },
  td: {
    padding: "10px",
    textAlign: "center",
  },
  te: {
    width: "40%",
    padding: "10px",
  },
  tr: {
    borderTop: "1px solid #E5E5E5",
  },
  thead: {
    backgroundImage:
      "linear-gradient(180deg,rgba(255, 238, 209, 1), rgba(255, 251, 244, 0.05))",
    backgroundSize: "100%",
    backgroundRepeat: "repeat",
  },
  dashboardWrapper: {
    fontFamily: "Nunito",
    color: "#1A1A19",
    display: "flex",
    flexDirection: "row",
    justifyContent: "Space-between",
    alignItems: "flex-start",
    height: "100vh",
    backroundColor: "#FAFAFB",
  },
  rightbarWrapper: {
    flex: 6,
    justifyContent: "space-between",
    alignItems: "flex-start",
    height: "20vh",
  },
  dashboardMenu: {
    fontFamily: "Nunito",
    flex: 8,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "space-between",
    width: "100%",
    padding: "40px",
  },
  dashboardMenuLeftSide: {
    width: "55%",
  },
  dashboardMenuRightSide: {
    width: "40%",
  },
  storeInfo: {
    height: "60vh",
    position: "relative",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  dashWrap: {
    display: "flex",
    marginTop: "5vh",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "70vh",
    overflowY: "scroll",
    width: "100%",
  },
  salesWrapper: {
    padding: "10px",
    backgroundColor: "white",
    borderRadius: "5px",
    minHeight: "70vh",
    maxHeight: "fit-content",
    marginBottom: "10vh",
    width: "100%",
    boxShadow: "-7px 7px 14px rgba(248, 141, 43, 0.07)",
  },
  salesHeader: {
    padding: "15px 5px 0px 5px",
    fontWeight: "700",
    fontSize: "24px",
    width: "100%",
    position: "relative",
  },

  addMeal: {
    padding: "10px",
    backgroundColor: "white",
    maxHeight: "fit-content",
    borderRadius: "5px",
    width: "55%",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
  },
  category: {
    padding: "10px",
    backgroundColor: "white",
    maxHeight: "352px",
    borderRadius: "5px",
    width: "35%",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
  },
  addMealText: {
    color: "#717171",
    fontWeight: "700",
    fontSize: "24px",
    padding: "10px",
  },
  inputWrapper: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inputLabel: {
    width: "40%",
    padding: "10px",
    fontSize: "16px",
    fontWeight: "400",
  },
  inputField: {
    width: "65%",
    padding: "10px",
  },
  choosePicture: {
    height: "30vh",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: "10px",
    backgroundColor: "white",
    maxHeight: "fit-content",
    borderRadius: "5px",
    width: "65%",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
  },
  inputFieldTextArea: {
    width: "65%",
    padding: "10px",
  },
  imageWrapper: {
    width: "55%",
    height: "100%",
    border: "1px solid black",
    borderStyle: "dotted",
    textAlign: "center",
    alignItems: "center",
  },
  chooseButton: {
    color: "#FEC72E",
    fontWeight: "700",
    margin: "auto",
    marginTop: "30%",
    width: "70%",
    padding: "5px",
    borderRadius: "5px",
    border: "1px solid #FEC72E",
  },
  buttonStyle: {
    backgroundColor: "rgba(254, 181, 46, 1)",
    color: "rgba(189, 0, 0, 1)",
    padding: "10px",
    fontFamily: "Nunito",
    fontWeight: "500",
    margin: "5px",
    borderRadius: "5px",
    textDecorationLine: "none",
    textDecoration: "none",
  },
  addMealWrapper: {
    width: "100%",
    textAlign: "center",
    alignItems: "center",
  },
  bottomInputWrapper: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  centerDiv: {
    width: "50vw",
    height: "50vh",
    textAlign: "center",
    margin: "auto",
  },
  contentCenterDiv: {
    marginTop: "40%",
  },
  navWrapper: {
    backgroundColor: "#FEB52E",
    padding: "5vh",
    display: "flex",
    justifyContent: "space-between",
    fontFamily: "Nunito",
    position: "fixed",
    zIndex: 99999,
    width: "100vw",
    boxSizing: "border-box",
    top: "-5px",
  },
  navItem: {
    width: "40%",
    alignSelf: "center",
    fontFamily: "Nunito",
  },
  navItemContent1: {
    float: "right",
    marginRight: "50px",
    cursor: "pointer",
    fontFamily: "Nunito",
    fontWeight: "700",
  },
  navItemContent2: {
    color: "#BD0000",
    marginLeft: "50px",
    cursor: "pointer",
    fontWeight: "700",
  },
  navItemContent3: {
    marginLeft: "50px",
    cursor: "pointer",
    backgroundColor: "#BD0000",
    padding: "8px",
    borderRadius: "5px",
    color: "#FEB52E",
    fontWeight: "400",
  },
  dashboardLeftBar: {
    height: "fit-content",
    minHeight: "fit-content",
    flex: "1",
    padding: "2%",
    boxShadow: "20px 10px 20px #88888",
    alignItems: "center",
    backgroundColor: "white",
  },
  listWrapper: {
    padding: "5px",
    alignItems: "center",
    width: "100%",
    fontFamily: "Nunito",
  },
  unorderedList: {
    fontFamily: "Nunito",
    listStyle: "none",
    justifyContent: "center",
    width: "100%",
    fontFamily: "Nunito",
  },
  list: {
    listStyle: "none",
    textDecoration: "none",
    margin: "0px 0px 20px 0px ",
    width: "100%",
    fontSize: "1rem",
    fontWeight: "500",
    padding: "0px",
    fontFamily: "Nunito",
  },
  image: {
    alignItems: "center",
    paddingBottom: "15%",
  },
  carouseltemWrapper: {
    width: "50%",
    position: "relative",
    height: "50%",
    textAlign: "left",
    padding: "10px",
    fontFamily: "Nunito",
  },
  carouselItem: {
    position: "absolute",
    color: "white",
    marginTop: "45vh",
    padding: "20px",
    fontFamily: "Nunito",
  },
  homeBodySection: {
    background:
      "linear-gradient(161.95deg, #FFEED1 18.44%, rgba(255, 251, 244, 0.05) 93.99%)",
  },
  weOfferWrapper: {
    width: "100%",
    position: "relative",
    margin: "auto",
    top: "100vh",
    fontFamily: "Nunito",
    height: "fit-content",
  },
  weOfferHeader: {
    width: "50%",
    textAlign: "center",
    margin: "auto",
    padding: "5vh",
  },
  weOfferItems: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "space-between",
    textAlign: "center",
  },
  weOfferItemWrapper: {
    width: "20%",
    alignItems: "center",
    textAlign: "center",
  },
  weOfferItemHead: {
    backgroundColor: "#FFF4D5",
    borderRadius: "50%",
    boxShadow: "-7px 7px 14px rgba(248, 141, 43, 0.1)",
    width: "100px",
    minHeight: "100px",
    alignItems: "center",
    textAlign: "center",
    justifyContent: "center",
  },
  moreDetailsWrapper: {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "30vh",
    alignItems: "center",
    width: "80%",
    margin: "auto",
    position: "relative",
  },
  moreDetailsImage: {
    width: "50%",
    zIndex: "9999",
  },
  moreDetailsText: {
    width: "40%",
    padding: "5%",
    textAlign: "center",
  },
  overlayDetails: {
    transform: "rotate(7deg)",
    background: "linear-gradient(101.63deg, #D76666, #FEDD82)",
    width: "600px",
    height: "350px",
    zIndex: "-9999",
    position: "absolute",
    borderRadius: "20px",
    clear: "both",
    top: "200px",
    left: "-30px",
  },
  overlay2Details: {
    transform: "rotate(355deg)",
    background: "linear-gradient(101.63deg, #D76666, #FEDD82)",
    width: "600px",
    height: "350px",
    zIndex: "-9999",
    position: "absolute",
    borderRadius: "20px",
    clear: "both",
    top: "200px",
    right: "-10px",
  },
  newsLetterWrapper: {
    width: "80%",
    margin: "auto",
    padding: "5vh",
    justifyContent: "center",
  },
  searchBarWrapper: {
    width: "100%",
    margin: "auto",
    textAlign: "center",
    padding: "20px",
  },
  searchInput: {
    border: "none",
    borderRadius: "8px",
    padding: "8px",
    width: "50%",
    boxShadow: "-7px 7px 14px rgba(248, 141, 43, 0.1)",
    backround: "#FFFFFF",
  },
  iconWrapper: {
    margin: "10px",
  },

  footerWrapper: {
    backgroundColor: "#FEB52E",
    padding: "10vh",
    width: "100%",
    fontFamily: "Nunito",
    marginTop: "10vh",
  },
  linkUps: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  },
  linkUpElements: {
    width: "20%",
    marginTop: "10vh",
  },
  ul: {
    listStyle: "none",
  },
  li: {
    paddingTop: "5vh",
  },
  socialMediaIconsWrapper: {
    width: "100%",
    justifyContent: "center",
    textAlign: "center",
    padding: "5vh",
  },
  socialMediaIcons: {
    margin: "5vh",
  },
  appBtn: {
    border: "1px solid #BD0000",
    borderRadius: "5px",
    padding: "15px 10px",
    marginTop: "5vh",
    color: "#BD0000",
    width: "70%",
    display: "flex",
    justifyContent: "space-between",
    cursor: "pointer",
  },

  th: {
    color: "black",
    fontWeight: "700",
    padding: "10px",
    textAlign: "center",
  },
  td: {
    padding: "20px",
    textAlign: "center",
  },
  te: {
    width: "40%",
    padding: "10px",
  },
  tr: {
    borderTop: "1px solid #E5E5E5",
  },
  thead: {
    backgroundImage:
      "linear-gradient(180deg,rgba(255, 238, 209, 1), rgba(255, 251, 244, 0.05))",
    backgroundSize: "100%",
    backgroundRepeat: "repeat",
  },
  completed: {
    border: "none",
    borderRadius: "20px",
    backgroundColor: "#FEC72E",
    fontFamily: "Nunito",
    padding: "10px",
    textAlign: "center",
    alignItems: "center",
    color: "#1A1A19",
    fontWeight: "400",
  },
  pending: {
    border: "none",
    borderRadius: "20px",
    backgroundColor: "#717171",
    fontFamily: "Nunito",
    padding: "10px",
    textAlign: "center",
    alignItems: "center",
    color: "#FAFAFB",
    fontWeight: "400",
  },
  cancelled: {
    border: "none",
    borderRadius: "20px",
    backgroundColor: "#BD0000",
    fontFamily: "Nunito",
    padding: "10px",
    textAlign: "center",
    alignItems: "center",
    color: "#FAFAFB",
    fontWeight: "400",
  },
  messagesWrapper: {
    position: "fixed",
    zIndex: "9999",
    bottom: "10vh",
    right: "5vh",
    borderRadius: "50%",
    backgroundColor: " #FEC72E",
    width: "fit-content",
    padding: "20px",
    boxShadow: "-3px 3px 4px 2px rgba(192, 127, 7, 0.18)",
  },
  messages: {
    padding: "5px",
  },
  storeMenu: {
    backgroundColor: "#FFFFFF",
    width: "60%",
    margin: "auto",
    minHeight: "50vh",
    maxHeight: "75vh",
    margin: "5vh auto auto auto",
    overflowY: "scroll",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
    borderRadius: "15px",
  },
  storeMenu1: {
    backgroundColor: "#FFFFFF",
    width: "90%",
    margin: "auto",
    minHeight: "50vh",
    maxHeight: "75vh",
    margin: "5vh auto auto auto",
    overflowY: "scroll",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
    borderRadius: "15px",
  },
  storeMenu2: {
    backgroundColor: "#FFFFFF",
    width: "80%",
    margin: "auto",
    minHeight: "65vh",
    maxHeight: "80vh",
    overflowY: "scroll",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
    borderRadius: "5px",
  },
  storeMenuContentWrapper: {
    padding: "10px 20px",
  },
  storeMenuContentFields: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "space-between",
    width: "100%",
  },
  storeMenuFirstField: {
    width: "30%",
    padding: "20px",
  },
  storeMenuFirstField2: {
    width: "50%",
    padding: "20px",
  },
  storeMenuSecondField: {
    width: "70%",
    padding: "20px",
  },
  storeMenuSecondField2: {
    width: "50%",
    padding: "20px",
  },
  storeMenuInputField: {
    border: "none",
    width: "90%",
    borderBottom: "1px dashed #717171",
    padding: "0px",
  },
  storeMenuInputField2: {
    border: "none",
    width: "60%",
    borderBottom: "1px dashed #717171",
    padding: "1px",
  },
  storeMenuChooseFileButton: {
    border: "1px solid #717171",
    color: "#717171",
    fontSize: "14px",
    padding: "5px",
    borderRadius: "5px",
  },
  storeMenuLogoPicker: {
    backgroundColor: "#FFFFFF",
    borderRadius: "10px",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
    height: "30vh",
    width: "90%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "space-between",
  },
  storeMenuLogoDisplay: {
    height: "80%",
    width: "40%",
    border: "1px dashed #717171",
    alignSelf: "center",
    margin: "10px",
  },
  storeMenuTextAreaField: {
    width: "90%",
    border: "1px dashed #717171",
    padding: "5px",
    height: "20vh",
  },
  storeMenuSaveSettingsWrapper: {
    width: "100%",
    justifyContent: "right",
    textAlign: "right",
  },
  storeMenuSaveSettingsButton: {
    padding: "8px",
    color: "#DB0000",
    fontWeight: "700",
    backgroundColor: "#FEB52E",
    alignSelf: "right",
    margin: "5vh",
    borderRadius: "5px",
  },
  formWrapper: {
    backgroundColor: "#FFFFFF",
    boxShadow: "0px 4px 10px 4px rgba(121, 121, 130, 0.15)",
    width: "100%",
    height: "fit-content",
    minHeight: "100vh",
    fontFamily: "Nunito",
    padding: "0px 0px 20px 0px",
    margin: "10px",
  },
  daysWorkHours: {
    width: "10%",
  },
  daysInputFieldWrapper: {
    width: "60%",
  },
  daysInputField: {
    border: "1px dashed #717171",
    padding: "3px",
    width: "70px",
    margin: "10px",
  },
  closedButton: {
    padding: "3px",
    border: "1px solid #717171",
    boxSizing: "border-box",
    borderRadius: "2px",
    color: "#717171",
  },
  decoratedText: {
    color: "#FEB52E",
  },
  saveSettingsButton: {
    padding: "5px",
    border: "1px solid #FEB52E",
    color: "#BD0000",
    borderRadius: "5px",
    marginLeft: "80px",
    backgroundColor: "#FEB52E",
  },
  chooseFileButton: {
    border: "1px solid grey",
    borderRadius: "5px",
    margin: "auto",
    marginBottom: "25%",
    width: "30%",
    padding: "5px",
    cursor: "pointer",
  },
  storeCardWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "45%",
    height: "40vh",
    padding: "5vh",
  },
  storeNameWrapper: {
    color: " #1A1A19",
    fontFamily: "Nunito",
    fontWeight: "700",
    fontSize: "24px",
  },
  storeCardLeftSide: {
    width: "30%",
  },
  storeCardRightSide: {
    width: "60%",
  },
  storeCardRightSideWrapper: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "left",
  },
  storeLocationWrapper: {
    color: "#000000",
    fontSize: "14px",
    fontWeight: "400",
  },
};
